import type { IntentModel } from './types'

export const intentModel: IntentModel = {
  meta: {
    version: '0.7.0',
    project: 'ACFS VBS Pickup Portal',
    lastUpdated: '2026-03-21',
    status: 'draft',
  },
  actors: [
    {
      id: 'lsp',
      name: 'Logistics Service Provider (LSP)',
      description: 'Core registered user. Umbrella term covering NVOCC, wholesale Freight Forwarder, Freight Forwarder, Transporter, Farmers, and Customer/Clearing agents. Each LSP sees only shipments allocated to them. Can delegate to another LSP or a one-off P4TC. Replaces the previous WFF/FF/Carrier actor split. Note: roles are contextual per HBL — the same organisation can appear at different levels (e.g. top-level party on one HBL, delegatee on another). Visibility and role enforcement must be HBL-scoped, not user-scoped.',
      auth: 'Username + password. Created by ACFS admin in the portal.',
      responsibilities: [
        { id: 'lsp:r1', description: 'View list of assigned HBLs with shipment status, milestone, payment, delegation, and booking info. Data auto-synced on login and on subsequent integration layer calls.' },
        { id: 'lsp:r2', description: 'Select one or multiple shipments to take action on (delegate or book).' },
        { id: 'lsp:r3', description: 'Delegate shipments to an existing LSP (search and select) or add a new one-off LSP, which creates a P4TC with email + secure link. Per HBL — if delegated, LSP cannot also book directly on that same HBL (BR-004).' },
        { id: 'lsp:r4', description: 'Book pickup directly: system validates booking readiness (unpacked + customs cleared + DOs present) → upload missing docs → load calculation + pricing → select slot → enter truck and driver details (select existing or add new, scoped to account) → accept T&Cs + site induction → make payment (Stripe/Compay) → receive booking confirmation with reference number. Requires HBL milestone "unpacked" or later (BR-001).' },
        { id: 'lsp:r5', description: 'Request missing docs when DOs are unavailable. Booking process is aborted (offline) until DO is received.' },
        { id: 'lsp:r6', description: 'Upload Delivery Order for downstream enforcement.' },
        { id: 'lsp:r7', description: 'Flag an HBL as under-bond. Manually set in portal — not synced from Maximus.' },
        { id: 'lsp:r8', description: 'Modify booking before cutoff: change slot date/time and HBLs (add/remove) before booking cutoff. Change truck/driver at any time until shipment is collected. Cost-impacting changes after cutoff require ACFS (BR-015).' },
      ],
    },
    {
      id: 'p4tc',
      name: 'Party to Collect (P4TC)',
      description: 'Tertiary/one-off user with no portal credentials. Receives email with shipment roster and document portal URL. No persistent account or history. Replaces previous "One-off Customer" and "Freight Forwarder" (magic-link) actors.',
      auth: 'Magic link + OTP. No login required — clicks link from email, verifies via OTP. Portal access scoped to assigned shipments only. Link expires on collection.',
      responsibilities: [
        { id: 'p4tc:r1', description: 'Access portal via emailed link (no login). Verify identity with OTP.' },
        { id: 'p4tc:r2', description: 'View list of assigned HBLs from the delegation.' },
        { id: 'p4tc:r3', description: 'Delegate shipments further: enter P4TC name + email ID, optionally upload new DO. System sends email with shipment roster and secure link to the new P4TC.' },
        { id: 'p4tc:r4', description: 'Book pickup: validate booking readiness → load calculation + pricing → select slot → enter truck and driver details (name, license#, phone — no saved drivers for P4TC) → accept T&Cs + site induction → make payment → receive booking confirmation with reference.' },
        { id: 'p4tc:r5', description: 'Upload missing DO or contact ACFS for support if DO is unavailable.' },
      ],
    },
    {
      id: 'driver',
      name: 'Driver',
      description: 'Secondary user. No portal access. No direct system communication — the booking party manages driver rostering externally and forwards booking details to the driver.',
      auth: 'No portal auth. No system emails. Booking party forwards confirmation externally.',
      responsibilities: [
        { id: 'driver:r1', description: 'Receive booking reference from booking party (forwarded externally — system does NOT email the driver directly).' },
        { id: 'driver:r2', description: 'Present booking reference and identity at gatehouse for pickup verification.' },
      ],
    },
    {
      id: 'acfs',
      name: 'ACFS Internal',
      description: 'Internal ACFS staff. Two sub-roles: Admin (full privileges) and User (predefined/restricted privileges). Manages HBL assignment, slot configuration, booking operations, DO validation, pickup verification, and user management.',
      auth: 'SSO-based access. Admin and User sub-roles with predefined privileges.',
      responsibilities: [
        { id: 'acfs:r1', description: 'HBL Assignment (remedial/optional): manually assign or reassign HBLs to LSPs via searchable dropdown (search LSP by name → assign). Same UX for reassignment — search and select a different LSP. System lists unassigned FAK shipments. Low priority for Phase 1 — data fix preferred over UI.' },
        { id: 'acfs:r2', description: 'ECST Assignment: assign ECST to shipments. Parked for Phase 1 — flow details to be defined later.' },
        { id: 'acfs:r3', description: 'Slot Configuration: select site → select days of week → set start/end time per slot (flexible, overlapping allowed) → configure booking cutoff and change cutoff (relative day + time, e.g. "previous working day, 4 PM") → optionally set heat map threshold value (nice-to-have) → block holidays via calendar overlay → save/update slots.' },
        { id: 'acfs:r4', description: 'Manage Booking: search bookings by booking ref# or by truck/driver details → view details (slot date/time, booking party, HBLs, fees paid, driver/truck) → inline edit: change pickup slot, change driver/truck, add/remove HBLs. All edits available on non-cancelled/non-collected bookings. Admin can override cutoffs. When HBLs are added/removed, fee total recalculates but no additional payment is collected (fee-free modifications for Phase 1). No truck capacity validation — that is the carrier\'s responsibility. Booking update notification sent via email to booking party.' },
        { id: 'acfs:r5', description: 'DO Validation (separate from pickup verification): view list of bookings with unvalidated DOs → validate DO against lowest-level HBL details → mark as validated. HBL-centric, not booking-centric. Can be done by offshore team. Prioritise by slot date/time.' },
        { id: 'acfs:r6', description: 'Pickup Verification: search bookings by ref# or truck/driver → view details + DO validation status + audit tracking → validate or reject. If validated, change booking status to "processed". If not validated, booking is flagged. Includes DO validation if not already done.' },
        { id: 'acfs:r7', description: 'User Management: create, update, and remove users (LSP and ACFS internal). Configure feature permissions per user.' },
        { id: 'acfs:r8', description: 'Override missing DO requirement. Restricted to Admin role. Audit trail with reason required. One-time per HBL, lives until collected.' },
        { id: 'acfs:r9', description: 'FOC rebooking for no-shows: admin edits the pickup slot (and optionally driver/truck) on the existing booking — no new booking created. Fee-free. No separate FOC rebook action — uses the same inline edit capability as acfs:r4.' },
        { id: 'acfs:r10', description: 'Flag an HBL as under-bond.' },
        { id: 'acfs:r11', description: 'Partially process bookings — clear HBLs proceed while blocked ones are rebooked separately.' },
        { id: 'acfs:r12', description: 'Edit HBL details and update milestones/statuses manually when corrections are needed.' },
        { id: 'acfs:r13', description: 'Edit delegation — reassign or revoke delegation between parties.' },
      ],
    },
    {
      id: 'gatehouse',
      name: 'Gatehouse',
      description: 'ACFS gatehouse staff who verify and confirm physical vehicle entry/exit for pickups. Part of the Pickup Verification flow.',
      auth: 'SSO via OAuth/Okta.',
      responsibilities: [
        { id: 'gatehouse:r1', description: 'Verify booking reference, driver identity, and truck rego on arrival.' },
        { id: 'gatehouse:r2', description: 'Confirm vehicle exit to mark booking as collected.' },
      ],
    },
  ],
  entities: [
    {
      id: 'hbl',
      name: 'House Bill of Lading (HBL)',
      description: 'Primary tracking unit for a shipment. Sourced from Maximus via periodic batch (once or twice daily). Two orthogonal dimensions: milestone (physical progress) and HBL status (delegation/booking state). HBLs exist in a hierarchy: AGS issues master HBLs (often 500-prefix), freight forwarders issue lower-level HBLs (e.g. 4033-prefix for Mondial). Mostly 1:1 parent-child relationship. The portal primarily deals with the lowest-level HBL as the primary identifier. Full audit trail lives on HBL — shows all hops, delegation chain, assignment changes, and status transitions.',
      key_fields: [
        { name: 'hbl_number', type: 'string', description: 'Primary identifier — lowest-level house bill number from Maximus.' },
        { name: 'alt_hbl_reference', type: 'string', description: 'Alternative/parent HBL reference (e.g. AGS master HBL). Optional — present when hierarchy exists. Relationship established via AGS data feed, not Maximus.', warn: 'Exact data source for HBL hierarchy relationship TBD — Matt and William resolving (OQ-034).' },
        { name: 'container_number', type: 'string', description: 'Container reference — ties HBL to the top-level container.' },
        { name: 'ocean_bl', type: 'string', description: 'Ocean bill of lading. Multiple containers may share one ocean BL.' },
        { name: 'consignee', type: 'string', description: 'Next party in the chain. Data source is AGS feed (not ICS/Maximus — too inconsistent). Identified by account name or account code.' },
        { name: 'weight_kg', type: 'number', description: 'Weight measurement for fee calculation.' },
        { name: 'volume_m3', type: 'number', description: 'Volumetric measurement for fee calculation.' },
        { name: 'chargeable_weight', type: 'number', description: 'Max of weight vs volume per HBL. Used for fee calculation: chargeable_weight × rate. Calculated and stored as a field.' },
        { name: 'quantity', type: 'number', description: 'Number of packages (e.g. 3 boxes). Optional — may not be required for decision-making.' },
        { name: 'pack_type', type: 'string', description: 'Package type description. Optional — may not be required for decision-making.' },
        { name: 'description', type: 'string', description: 'Goods description. Two source fields exist in Maximus: "description" and "marks and numbers" — may consolidate.' },
        { name: 'milestone', type: "'on_vessel' | 'at_wharf' | 'in_yard' | 'unpacked' | 'collected'", description: 'Physical progress milestone. Linear progression. Sourced from Maximus batch sync.' },
        { name: 'hbl_status', type: "'unassigned' | 'assigned' | 'delegated' | 'booked'", description: 'Delegation/booking status. Separate dimension from milestone. "assigned" means allocated to an LSP. "delegated" means LSP has passed to another party. "booked" means pickup is scheduled.' },
        { name: 'customs_clearance_status', type: 'string', description: 'Customs clearance state including quarantine. Must be fully cleared (not partial) for booking. Shown in HBL table. Sourced from Maximus — update frequency from ICS unclear.' },
        { name: 'under_bond', type: 'boolean', description: 'Flag — NOT a lifecycle state. Goods moving between bonded facilities before customs clearance (Australian Border Force customs bond). Manually set by LSP/ACFS in portal. Movement permission replaces DO requirement. Not synced from Maximus.' },
        { name: 'under_bond_verified', type: 'boolean', description: 'Whether ACFS has verified the under-bond marking. Verification happens outside the portal; portal records the result. Set by ACFS staff only.' },
        { name: 'storage_fee_flag', type: 'boolean', description: 'Visual indicator that storage fees apply. Derived from last_free_storage_date — auto-calculated, not manually set.' },
        { name: 'last_free_storage_date', type: 'date', description: 'Last date of free storage. After this date, storage_fee_flag is automatically set to true. Sourced from Maximus or set by ACFS.' },
        { name: 'release_type', type: "'do_required' | 'free_release'", description: 'Determines DO requirements. Phase 1 supports two types: "do_required" (default — DO must be uploaded and validated) and "free_release" (no DO needed for that tier). Under-bond HBLs skip DO requirement entirely via the under_bond flag.' },
        { name: 'assigned_lsp', type: 'string', description: 'LSP this HBL is allocated to. Set by ACFS during HBL/WFF assignment or auto-assigned from data.' },
      ],
      lifecycle: {
        states: ['on_vessel', 'at_wharf', 'in_yard', 'unpacked', 'collected'],
        transitions: [
          { from: 'on_vessel', to: 'at_wharf', trigger: 'Vessel arrives at port', guard: 'Maximus batch sync' },
          { from: 'at_wharf', to: 'in_yard', trigger: 'Container moved to yard' },
          { from: 'in_yard', to: 'unpacked', trigger: 'Container unpacked at warehouse' },
          { from: 'unpacked', to: 'collected', trigger: 'Goods physically picked up from warehouse', guard: 'Booking in "processed" state + gatehouse confirms exit' },
        ],
        warn: 'Milestones only — delegation and booking are tracked via hbl_status, a separate dimension. Delegation can happen at any milestone (BR-001). Booking requires milestone "unpacked" or later (BR-001).',
      },
    },
    {
      id: 'booking',
      name: 'Booking',
      description: 'Groups one or more HBLs into a pickup window with driver/truck details. Created by LSP or P4TC. No truck type distinction for Phase 1 — booking party is responsible for bringing the correct truck. Slim audit trail at booking level (created, payment confirmed). Full hop history lives on the HBL entity instead. "Collected" status is derived — booking becomes collected when all its HBLs reach the "collected" milestone (no manual status change).',
      key_fields: [
        { name: 'booking_id', type: 'string', description: 'System-generated unique reference number.' },
        { name: 'pickup_window', type: 'PickupWindow', description: 'Selected date/time slot.' },
        { name: 'hbl_ids', type: 'string[]', description: 'HBLs included in this booking. Can span multiple LSPs.' },
        { name: 'driver_name', type: 'string', description: 'Driver performing pickup.' },
        { name: 'driver_license', type: 'string', description: 'Driver license number.' },
        { name: 'truck_rego', type: 'string', description: 'Vehicle registration.' },
        { name: 'fee_amount', type: 'number', description: 'Sum of (chargeable_weight × rate) per HBL + minimum charge. Backend-calculated and returned per HBL from the API. Rate and minimum charge are backend-configurable. Frontend displays calculated values only — no fee logic in frontend.' },
        { name: 'booking_party', type: 'string', description: 'LSP or P4TC who created the booking.' },
        { name: 'tc_accepted', type: 'boolean', description: 'Whether booking party accepted terms and conditions.' },
        { name: 'site_induction_accepted', type: 'boolean', description: 'Whether driver site induction was acknowledged. Skipped if driver already has site_induction = true.' },
      ],
      lifecycle: {
        states: ['draft', 'booked', 'pending_processing', 'processed', 'collected', 'cancelled'],
        warn: '"collected" is a derived status — automatically set when all HBLs in the booking reach the "collected" milestone. No manual status change.',
        transitions: [
          { from: 'draft', to: 'booked', trigger: 'LSP or P4TC confirms, accepts T&Cs + site induction, and pays', guard: 'All HBLs at milestone "unpacked" or later + fully customs cleared + release conditions met + missing docs uploaded + T&Cs accepted' },
          { from: 'booked', to: 'pending_processing', trigger: 'ACFS staff begins pickup verification' },
          { from: 'pending_processing', to: 'processed', trigger: 'ACFS validates DOs + audit tracking and marks ready. Partial processing allowed — clear HBLs proceed, blocked ones rebook separately.' },
          { from: 'processed', to: 'collected', trigger: 'Gatehouse confirms vehicle exit' },
          { from: 'booked', to: 'cancelled', trigger: 'LSP or ACFS cancels booking. Cancellation reason required (ACFS). Refund processed outside system.' },
        ],
      },
    },
    {
      id: 'slot',
      name: 'Pickup Slot',
      description: 'A configurable time window at a specific site. Configured by ACFS admin. No truck type distinction for Phase 1. Default granularity is hourly (1-hour slots) — ACFS configures available hours per day. Visual presentation uses primary color with varying opacity levels to show booking density per slot without exact numbers.',
      key_fields: [
        { name: 'slot_id', type: 'string', description: 'System-generated unique ID.' },
        { name: 'site', type: 'string', description: 'Physical site/location for pickup (references site entity).' },
        { name: 'days_of_week', type: 'string[]', description: 'Days this slot template applies to (e.g. Monday-Friday).' },
        { name: 'start_time', type: 'time', description: 'Slot start time.' },
        { name: 'end_time', type: 'time', description: 'Slot end time.' },
        { name: 'booking_cutoff', type: '{ relative_day: string, time: string }', description: 'Booking cutoff — relative day (e.g. "previous_working_day", "same_day") + time (e.g. "16:00"). Bookings not accepted after this point.' },
        { name: 'change_cutoff', type: '{ relative_day: string, time: string }', description: 'Change cutoff — same format as booking cutoff. Changes to slot/date/HBLs not allowed after this point (truck/driver changes exempt).' },
        { name: 'heat_map_threshold', type: 'number', description: 'Threshold value for density indicator. Primary color with varying opacity levels applied to slot cards (low opacity = empty, high opacity = busy). No exact booking counts shown. Nice-to-have for Phase 1.' },
        { name: 'is_blocked', type: 'boolean', description: 'Whether slot is blocked due to holiday/blackout date.' },
      ],
      lifecycle: {
        states: ['active', 'blocked', 'past'],
        transitions: [
          { from: 'active', to: 'blocked', trigger: 'ACFS adds blackout/holiday date' },
          { from: 'blocked', to: 'active', trigger: 'ACFS removes blackout/holiday date' },
          { from: 'active', to: 'past', trigger: 'Slot end time passes' },
        ],
      },
    },
    {
      id: 'site',
      name: 'Site',
      description: 'Physical warehouse/pickup location. Seeded directly in the database — no admin CRUD UI for Phase 1.',
      key_fields: [
        { name: 'site_name', type: 'string', description: 'Human-readable site name (e.g. "Port Botany Warehouse").' },
        { name: 'branch_code', type: 'string', description: 'Branch code (e.g. "SY", "MB", "BR"). Multiple sites can share a branch code.' },
      ],
      lifecycle: {
        states: ['active'],
        transitions: [],
        warn: 'Static entity — DB-seeded, no state transitions in Phase 1.',
      },
    },
    {
      id: 'driver_record',
      name: 'Driver Record',
      description: 'Saved driver details for reuse across bookings. Built up organically by booking parties — no pre-population. Scoped per LSP account — drivers are NOT globally visible across accounts.',
      key_fields: [
        { name: 'driver_name', type: 'string', description: 'Driver full name.' },
        { name: 'driver_license', type: 'string', description: 'Driver license number. Paired with name.' },
        { name: 'truck_rego', type: 'string', description: 'Default vehicle registration.' },
        { name: 'site_induction', type: 'boolean', description: 'Whether driver has completed site induction. If true, site induction acceptance is skipped during booking.' },
      ],
      lifecycle: {
        states: ['active'],
        transitions: [],
        warn: 'Static entity — created during booking flow, no state transitions.',
      },
    },
    {
      id: 'delivery_order',
      name: 'Delivery Order (DO)',
      description: 'Document required per HBL for pickup authorization. One-to-many relationship: each HBL can have multiple DOs (one per delegation tier in the hierarchy). Each DO is validated individually by ACFS. Uploaded by LSP or P4TC, validated by ACFS. Each tier in the HBL hierarchy uploads independently — no inheritance. Free release removes the DO requirement for that tier. Under-bond HBLs skip DO requirement entirely.',
      key_fields: [
        { name: 'do_id', type: 'string', description: 'System-generated unique ID.' },
        { name: 'hbl_id', type: 'string', description: 'HBL this DO belongs to.' },
        { name: 'uploaded_by', type: 'string', description: 'LSP or P4TC who uploaded the document.' },
        { name: 'upload_date', type: 'date', description: 'When the DO was uploaded.' },
        { name: 'document_url', type: 'string', description: 'Stored document reference/URL.' },
        { name: 'tier_level', type: 'string', description: 'Which level in the HBL hierarchy this DO covers. Each tier uploads independently.' },
      ],
      lifecycle: {
        states: ['not_provided', 'uploaded', 'pending_validation', 'validated', 'flagged', 'not_required'],
        transitions: [
          { from: 'not_provided', to: 'uploaded', trigger: 'LSP or P4TC uploads DO document' },
          { from: 'not_provided', to: 'not_required', trigger: 'HBL has free_release flag or under_bond flag' },
          { from: 'uploaded', to: 'pending_validation', trigger: 'ACFS begins DO review' },
          { from: 'pending_validation', to: 'validated', trigger: 'ACFS confirms DO matches HBL details' },
          { from: 'pending_validation', to: 'flagged', trigger: 'ACFS flags DO as incorrect — requires correction' },
          { from: 'flagged', to: 'uploaded', trigger: 'LSP or P4TC re-uploads corrected DO' },
        ],
      },
    },
    {
      id: 'delegation',
      name: 'Delegation',
      description: 'Records the delegation of one or more HBLs from one party to another. Tracks the chain of custody. Can be revoked by ACFS.',
      key_fields: [
        { name: 'delegation_id', type: 'string', description: 'System-generated unique ID.' },
        { name: 'delegator', type: 'string', description: 'LSP or P4TC who initiated the delegation.' },
        { name: 'delegatee', type: 'string', description: 'Target party — existing LSP (by ID) or new P4TC (by email).' },
        { name: 'delegation_method', type: "'existing_lsp' | 'one_off_p4tc'", description: 'Whether delegating to a registered LSP or creating a one-off P4TC.' },
        { name: 'hbl_ids', type: 'string[]', description: 'HBLs included in this delegation.' },
        { name: 'created_at', type: 'date', description: 'When the delegation was created.' },
      ],
      lifecycle: {
        states: ['active', 'revoked'],
        transitions: [
          { from: 'active', to: 'revoked', trigger: 'ACFS revokes the delegation (acfs:r13)', guard: 'HBLs revert to delegator' },
        ],
      },
    },
    {
      id: 'integration_maximus',
      name: 'Maximus Integration (Inbound)',
      description: 'Primary data source for HBL shipment data. Periodic batch sync from custom cargo table. Portal fetches data starting 7 days before vessel arrival. Provides lowest-level HBL references, weight, volume, customs clearance status, and consignee data. Does NOT provide HBL hierarchy relationships or freight forwarder party assignments.',
      key_fields: [
        { name: 'direction', type: 'string', description: 'Inbound — Maximus → Portal' },
        { name: 'frequency', type: 'string', description: 'Batch: once or twice daily. Auto-synced on LSP login.' },
        { name: 'data_provided', type: 'string', description: 'Lowest-level HBL number, weight, volume, customs clearance status (from ICS — update frequency unclear), consignee, quantity, pack type, description, marks and numbers.' },
        { name: 'data_not_provided', type: 'string', description: 'HBL hierarchy relationships (parent-child), freight forwarder party assignments, alternative HBL references.' },
        { name: 'status', type: 'string', description: 'Known — data structure understood. Frontend displays customs status as provided by the API. Staleness is a backend/integration concern. UI shows last sync timestamp if available.' },
      ],
      lifecycle: {
        states: ['active'],
        transitions: [],
        warn: 'Integration spec — no state transitions.',
      },
    },
    {
      id: 'integration_ags',
      name: 'AGS Data Feed (Inbound)',
      description: 'Provides master HBL references, HBL hierarchy (parent-child relationships), and freight forwarder party data (name, account code). Data is consistent (unlike ICS which has variations across organisations). Matt and William are defining the exact data format and delivery mechanism.',
      key_fields: [
        { name: 'direction', type: 'string', description: 'Inbound — AGS → Portal' },
        { name: 'frequency', type: 'string', description: 'TBD — Matt and William resolving (OQ-034).' },
        { name: 'data_provided', type: 'string', description: 'Master HBL references (500-prefix), HBL hierarchy (parent-child), freight forwarder party assignments (account name, account code), consignee at each level.' },
        { name: 'data_not_provided', type: 'string', description: 'Lowest-level HBL details (comes from Maximus instead).' },
        { name: 'status', type: 'string', description: 'BLOCKER — exact data format, delivery mechanism, and frequency TBD. This is the single biggest technical risk.', warn: 'Cannot build auto-assignment or HBL hierarchy without this feed. Matt and William working on it.' },
      ],
      lifecycle: {
        states: ['active'],
        transitions: [],
        warn: 'Integration spec — no state transitions.',
      },
    },
    {
      id: 'integration_payment',
      name: 'Payment Integration (Outbound)',
      description: 'Payment processing for booking fees. Stripe embedded checkout for Phase 1. Payment integration is abstracted behind a single checkout redirect — provider can be swapped later if needed.',
      key_fields: [
        { name: 'direction', type: 'string', description: 'Outbound — Portal → Stripe' },
        { name: 'frequency', type: 'string', description: 'Real-time — triggered on each booking.' },
        { name: 'provider', type: 'string', description: 'Stripe for Phase 1. Abstracted behind checkout redirect so provider can be swapped to Compay or another provider in a later phase.' },
      ],
      lifecycle: {
        states: ['active'],
        transitions: [],
        warn: 'Integration spec — no state transitions.',
      },
    },
    {
      id: 'integration_email',
      name: 'Email Notifications (Outbound)',
      description: 'Event-driven email notifications sent by the portal.',
      key_fields: [
        { name: 'direction', type: 'string', description: 'Outbound — Portal → Email' },
        { name: 'triggers', type: 'string', description: 'Delegation (secure link + OTP), booking confirmation (to account email), booking update (to booking party), booking cancellation (to booking party), DO flagged for correction (to booking party — Phase 1 sends to booking party, future may send to the party who uploaded the DO), user creation (welcome email with signin link).' },
        { name: 'not_sent_to', type: 'string', description: 'Driver — no system emails. Booking party forwards details externally.' },
      ],
      lifecycle: {
        states: ['active'],
        transitions: [],
        warn: 'Integration spec — no state transitions.',
      },
    },
    {
      id: 'integration_lsp_registry',
      name: 'LSP Registry Seed (One-time)',
      description: 'One-time bulk upload of LSP party data from AGS portal/party manager into the portal local DB.',
      key_fields: [
        { name: 'direction', type: 'string', description: 'Inbound — AGS → Portal (one-time)' },
        { name: 'frequency', type: 'string', description: 'One-time bulk upload at system launch. No ongoing sync.' },
        { name: 'data_provided', type: 'string', description: 'Company name, email, company ID, branch code.' },
      ],
      lifecycle: {
        states: ['active'],
        transitions: [],
        warn: 'Integration spec — one-time seed, no state transitions.',
      },
    },
  ],
  journeys: [
    {
      id: 'acfs-assigns-hbls',
      name: 'ACFS Assigns HBLs to LSP (Remedial)',
      primary_actor: 'acfs',
      preconditions: [
        'ACFS admin is logged in',
        'HBLs have been synced from Maximus',
        'Target LSP user exists in the portal',
        'Auto-assignment has failed or data issue exists',
      ],
      steps: [
        { order: 1, title: 'View unassigned shipments', detail: 'System lists FAK shipments that are unassigned or incorrectly assigned. Can filter by assignment status.' },
        { order: 2, title: 'Select and assign', detail: 'ACFS selects shipments and assigns them to an LSP. HBL status moves to "assigned". This is a remedial step — primary assignment comes from data integration.' },
      ],
      success_outcome: 'HBLs are assigned to the target LSP and visible in their shipment list on next login.',
      warn: 'Low priority for Phase 1. Matt indicated this may not be needed if auto-assignment is reliable within the 8-week timeline. Mark as optional.',
    },
    {
      id: 'acfs-configures-slots',
      name: 'ACFS Configures Pickup Slots',
      primary_actor: 'acfs',
      preconditions: [
        'ACFS admin is logged in',
        'Site exists in the database',
      ],
      steps: [
        { order: 1, title: 'Select site', detail: 'ACFS selects a site (one at a time — no multi-site simultaneous config).' },
        { order: 2, title: 'Configure slot template', detail: 'Select days of week (typically Mon-Fri). Set available hours per day (default: hourly granularity). Multiple slots per day allowed, flexible, overlapping OK.' },
        { order: 3, title: 'Configure cutoff rules', detail: 'Set booking cutoff (relative day + time, e.g. "previous working day, 4 PM") and change cutoff (same format). Relative to the slot day.' },
        { order: 4, title: 'Optional: set heat map threshold', detail: 'Set threshold value for density indicator. System shows primary color at varying opacity levels based on booking density. Nice-to-have.' },
        { order: 5, title: 'Block holidays', detail: 'Overlay holiday calendar to block specific dates.' },
        { order: 6, title: 'Save', detail: 'Save/update slot configuration.' },
      ],
      success_outcome: 'Pickup slots are configured and available for LSP/P4TC booking.',
    },
    {
      id: 'lsp-delegates-shipments',
      name: 'LSP Delegates Shipments',
      primary_actor: 'lsp',
      preconditions: [
        'LSP is logged in',
        'LSP has assigned HBLs visible in their list',
      ],
      steps: [
        { order: 1, title: 'Select shipments', detail: 'LSP views list of assigned HBLs with shipment status. Selects one or multiple shipments to delegate.' },
        { order: 2, title: 'Choose delegation target', detail: 'Either select an existing LSP (search and select from pre-populated registry — company name, email, branch code) or add a new one-off party (email only — creates a P4TC).' },
        { order: 3, title: 'System sends notification', detail: 'Email sent to the delegate with a message and secure link. No shipment data in the email body — all details visible after login/OTP.' },
      ],
      success_outcome: 'Shipments are delegated. Target LSP or P4TC receives email with secure access link. HBL status moves to "delegated".',
    },
    {
      id: 'lsp-books-pickup',
      name: 'LSP Books a Pickup',
      primary_actor: 'lsp',
      preconditions: [
        'LSP is logged in',
        'Selected HBLs are at milestone "unpacked" or later (BR-001)',
        'HBLs are not already delegated (BR-004)',
      ],
      steps: [
        { order: 1, title: 'Select shipments', detail: 'LSP selects one or multiple HBLs from their assigned list to book for pickup.' },
        { order: 2, title: 'Validate booking readiness', detail: 'System checks: (1) HBL milestone is "unpacked" or later, (2) fully customs cleared (including quarantine), (3) all applicable DOs are present. If docs missing, LSP can upload them or request missing docs (aborts booking — offline process).' },
        { order: 3, title: 'Load calculation + pricing', detail: 'System calculates fee per HBL: chargeable_weight (max of weight vs volume) × rate. Individual HBL charges summed + minimum charge = total fee.' },
        { order: 4, title: 'Select slot', detail: 'LSP selects an available hourly slot. Density indicator shows booking volume per slot using opacity levels (no exact numbers). Does not block booking.' },
        { order: 5, title: 'Enter truck and driver details', detail: 'Select existing driver from account-scoped list (search/dropdown) or enter new driver details (name, license, truck rego). New drivers are saved to the account for future reuse. P4TC users always enter fresh details.' },
        { order: 6, title: 'Accept T&Cs and site induction', detail: 'Booking party must accept: (1) booking terms and conditions (legal document), (2) driver site induction acknowledgement (document). If driver already has site_induction = true, the second acceptance is skipped.' },
        { order: 7, title: 'Make payment', detail: 'Payment via Stripe embedded checkout. Redirects to payment interface.' },
        { order: 8, title: 'Confirmation', detail: 'Booking confirmation with booking reference sent to the account email. No email sent to driver — booking party forwards details externally.' },
      ],
      success_outcome: 'Booking is confirmed with reference number. HBLs move to hbl_status "booked". Confirmation sent to account email.',
    },
    {
      id: 'lsp-modifies-booking',
      name: 'LSP Modifies a Booking',
      primary_actor: 'lsp',
      preconditions: [
        'LSP is logged in',
        'Booking exists in "booked" state',
      ],
      steps: [
        { order: 1, title: 'View booking details', detail: 'LSP opens an existing booking from their bookings list.' },
        { order: 2, title: 'Choose modification type', detail: 'LSP can: (a) change truck/driver details — allowed anytime until collection, (b) change slot date/time — allowed before change cutoff only, (c) add/remove HBLs — allowed before change cutoff only.' },
        { order: 3, title: 'System checks cutoff', detail: 'If change cutoff has passed: truck/driver changes proceed, but slot/HBL changes are blocked. Cost-impacting changes after cutoff require ACFS admin override (BR-015).' },
        { order: 4, title: 'Apply changes', detail: 'For truck/driver: update in-place. For slot: re-validate availability, recalculate fees if HBLs changed. For HBL removal: treated as partial cancellation with offline refund. For HBL addition: additional fee charged.' },
        { order: 5, title: 'Confirmation', detail: 'Updated booking confirmation sent to account email. Booking reference remains the same.' },
      ],
      success_outcome: 'Booking is updated with new details. Confirmation sent. If fee changed, payment difference handled.',
    },
    {
      id: 'p4tc-books-pickup',
      name: 'P4TC Books a Pickup',
      primary_actor: 'p4tc',
      preconditions: [
        'P4TC has received email with shipment roster and portal URL',
        'HBLs are at milestone "unpacked" or later',
      ],
      steps: [
        { order: 1, title: 'Access portal', detail: 'P4TC clicks link in email to access portal. No login required. Verifies via OTP sent to the same email. OTP verification serves as email security validation.' },
        { order: 2, title: 'View assigned HBLs', detail: 'P4TC sees list of assigned HBLs from the delegation.' },
        { order: 3, title: 'Choose action', detail: 'P4TC can either delegate shipments further (enter P4TC name + email, optionally upload new DO) or proceed to book pickup.' },
        { order: 4, title: 'Validate booking readiness', detail: 'System checks unpacked status, customs clearance, and DO presence. P4TC can upload missing DO or contact ACFS for support.' },
        { order: 5, title: 'Load calculation + pricing', detail: 'System calculates fees per HBL (chargeable_weight × rate + minimum charge). P4TC reviews pricing.' },
        { order: 6, title: 'Select slot', detail: 'Select available hourly slot. Density indicator shows booking volume using opacity levels (no exact numbers). Does not block.' },
        { order: 7, title: 'Enter truck and driver details', detail: 'Enter driver name, license#, truck rego. No saved driver list for P4TC (one-off users).' },
        { order: 8, title: 'Accept T&Cs and site induction', detail: 'Accept booking terms and conditions + driver site induction acknowledgement.' },
        { order: 9, title: 'Make payment', detail: 'Payment via Stripe/Compay.' },
        { order: 10, title: 'Confirmation', detail: 'Booking confirmation sent to P4TC email containing: booking reference, pickup slot (date/time), HBL numbers with weight/volume, fee total, and site address. No upstream delegation chain or LSP details exposed. No email to driver.' },
      ],
      success_outcome: 'Booking confirmed. Confirmation sent to P4TC email. HBLs move to "booked".',
    },
    {
      id: 'acfs-validates-dos',
      name: 'ACFS Validates Delivery Orders',
      primary_actor: 'acfs',
      preconditions: [
        'Bookings exist with unvalidated DOs',
      ],
      steps: [
        { order: 1, title: 'View unvalidated DOs', detail: 'ACFS views list of HBLs with unvalidated DOs. HBL-centric view — not booking-centric. Can filter/prioritise by slot date/time for upcoming bookings.' },
        { order: 2, title: 'Review DO against HBL', detail: 'View lowest-level HBL details alongside the uploaded DO. Slot date/time and booking reference shown for context.' },
        { order: 3, title: 'Validate or flag', detail: 'If DO matches HBL details, mark as validated. If DO is incorrect, flag for follow-up with booking party (using booking reference).' },
      ],
      success_outcome: 'DO is marked as validated for that HBL, or flagged for correction.',
      warn: 'DO validation can be done by offshore team independently from pickup verification. Same people doing pickup verification can also validate DOs, but DO validation is a separate capability.',
    },
    {
      id: 'acfs-verifies-pickup',
      name: 'ACFS Verifies Pickup',
      primary_actor: 'acfs',
      preconditions: [
        'Booking exists in "booked" or "pending_processing" state',
      ],
      steps: [
        { order: 1, title: 'Search booking', detail: 'ACFS searches bookings by booking ref# or by truck/driver details.' },
        { order: 2, title: 'Review details', detail: 'View booking details + DO validation status + audit tracking history. Includes DO validation if not already done.' },
        { order: 3, title: 'Validate or reject', detail: 'If all documents and details validate, change booking status to "processed". If validation fails, booking is flagged — does not proceed to collection.' },
      ],
      success_outcome: 'Booking status changed to "processed" and ready for gatehouse collection, or flagged for issues.',
      warn: 'Detailed field-level requirements for this view TBD — to be covered in next session with Matt.',
    },
    {
      id: 'lsp-cancels-booking',
      name: 'LSP Cancels a Booking',
      primary_actor: 'lsp',
      preconditions: [
        'LSP is logged in',
        'Booking exists in "booked" state',
      ],
      steps: [
        { order: 1, title: 'View bookings', detail: 'LSP views current and past bookings list.' },
        { order: 2, title: 'Open booking details', detail: 'LSP opens the booking they want to cancel.' },
        { order: 3, title: 'Cancel booking', detail: 'LSP initiates cancellation. Refund is processed outside the system (C-003).' },
      ],
      success_outcome: 'Booking is cancelled. HBLs revert to previous hbl_status. Refund handled offline by ACFS.',
    },
    {
      id: 'acfs-cancels-booking',
      name: 'ACFS Cancels a Booking',
      primary_actor: 'acfs',
      preconditions: [
        'ACFS admin is logged in',
        'Booking exists',
      ],
      steps: [
        { order: 1, title: 'Search booking', detail: 'ACFS searches by booking ref, truck rego, or driver name/license.' },
        { order: 2, title: 'Cancel booking', detail: 'ACFS initiates cancellation. Must provide cancellation reason.' },
        { order: 3, title: 'Notification', detail: 'Cancellation update sent to the booking party via email.' },
      ],
      success_outcome: 'Booking is cancelled. HBLs revert. Refund processed outside the system. Booking party notified.',
    },
    {
      id: 'p4tc-manages-booking',
      name: 'P4TC Manages Booking (One-off)',
      primary_actor: 'p4tc',
      preconditions: [
        'P4TC has an active booking',
      ],
      steps: [
        { order: 1, title: 'Contact ACFS', detail: 'P4TC contacts ACFS for any booking modifications. No self-service modification for one-off booking parties.' },
      ],
      success_outcome: 'ACFS handles the modification on behalf of the P4TC.',
    },
    {
      id: 'acfs-creates-user',
      name: 'ACFS Creates a User',
      primary_actor: 'acfs',
      preconditions: [
        'ACFS admin is logged in',
      ],
      steps: [
        { order: 1, title: 'Select user type', detail: 'Choose role: Logistics Service Provider, ACFS Admin, or ACFS User.' },
        { order: 2, title: 'Enter user details', detail: 'LSP: company name, company ID, branch code, contact name, contact email. Username + password based access. ACFS: company name = ACFS, company code, contact name, contact email. SSO-based access.' },
        { order: 3, title: 'System sends welcome email', detail: 'Welcome email with signin link sent to user. Link expires in 72 hours.' },
        { order: 4, title: 'User activates account', detail: 'LSP: clicks link and sets password. ACFS: clicks link and SSO login is requested. Successful login completes activation.' },
      ],
      success_outcome: 'User account is created and active. User can log in.',
    },
    {
      id: 'acfs-updates-user',
      name: 'ACFS Updates a User',
      primary_actor: 'acfs',
      preconditions: [
        'ACFS admin is logged in',
        'Target user exists',
      ],
      steps: [
        { order: 1, title: 'Select user', detail: 'Search and select the user to update. Available for LSP, ACFS Admin, and ACFS User roles.' },
        { order: 2, title: 'Update details', detail: 'LSP: can update everything except username. ACFS: can update everything except SSO details.' },
      ],
      success_outcome: 'User details are updated.',
    },
    {
      id: 'acfs-removes-user',
      name: 'ACFS Removes a User',
      primary_actor: 'acfs',
      preconditions: [
        'ACFS admin is logged in',
        'Target user exists',
      ],
      steps: [
        { order: 1, title: 'Select user', detail: 'Search and select the user to remove.' },
        { order: 2, title: 'Archive user', detail: 'User is archived on removal. Access is disabled and email notification is disabled.' },
      ],
      success_outcome: 'User is archived. Cannot log in. No further notifications sent.',
    },
  ],
  business_rules: [
    {
      id: 'BR-001',
      description: 'Delegation can happen at any milestone — no unpack gate. Booking requires all included HBLs to have milestone "unpacked" or later AND fully customs cleared (including quarantine). This means delegate button is always enabled; book button is gated by milestone + customs clearance.',
      applies_to: ['hbl', 'booking'],
      source: 'BRD s4.2 + discussion between Rahul, Roni, and Matt on 2026-03-17 and 2026-03-18',
    },
    {
      id: 'BR-002',
      description: 'Under-bond HBLs skip the DO requirement. Under-bond is a boolean flag set manually by LSP/ACFS staff in the portal. Not synced from Maximus. Verification happens outside the portal.',
      applies_to: ['hbl'],
      source: 'BRD s4.3 + discussion between Rahul, Roni, and Matt on 2026-03-17',
      warn: 'Under-bond is an LSP/ACFS manual flag — not a lifecycle or automated process.',
    },
    {
      id: 'BR-003',
      description: 'DO rules follow a multi-level hierarchy. Each level uploads its own DO independently — no inheritance or cascading. Bottom-most party must have ALL DOs present across all tiers. Free release removes the DO requirement for that tier.',
      applies_to: ['hbl', 'lsp', 'p4tc', 'acfs'],
      source: 'BRD s4.4 + discussion between Rahul, Roni, and Matt on 2026-03-17',
    },
    {
      id: 'BR-004',
      description: 'LSP can either delegate or book directly per HBL — never both on the same HBL. Mutual exclusivity enforced at the HBL level.',
      applies_to: ['hbl', 'lsp'],
      source: 'OQ-003 resolution + March 18 flow',
    },
    {
      id: 'BR-005',
      description: 'Slot cutoffs are relative day + time (e.g. "previous working day, 4 PM" or "same day, 10 AM"). Booking cutoff and change cutoff configured separately per slot template. Per-site configuration.',
      applies_to: ['booking', 'slot'],
      source: 'discussion between Roni and Matt on 2026-03-18',
    },
    {
      id: 'BR-006',
      description: 'No-show rebooking: ACFS admin edits the pickup slot (and optionally driver/truck) on the existing booking. No new booking is created. Fee-free for Phase 1. No separate FOC rebook button — uses inline edit on the booking detail view. LSP must call ACFS — no self-service for no-show rebooking.',
      applies_to: ['booking', 'acfs'],
      source: 'discussion between Rahul, Roni, and Matt on 2026-03-17 + discussion between Rahul and Roni on 2026-03-20',
    },
    {
      id: 'BR-007',
      description: 'ACFS can partially process bookings — HBLs that have cleared customs proceed while blocked ones are rebooked separately.',
      applies_to: ['booking', 'acfs'],
      source: 'discussion between Rahul, Roni, and Matt on 2026-03-17',
    },
    {
      id: 'BR-009',
      description: 'LSP can only view shipments allocated to them. Shipment visibility is scoped per LSP — no cross-LSP visibility.',
      applies_to: ['hbl', 'lsp'],
      source: 'March 18 flow diagram',
    },
    {
      id: 'BR-010',
      description: 'Data is auto-synced on LSP login and on the next call to the integration layer. No manual refresh needed.',
      applies_to: ['hbl', 'lsp'],
      source: 'March 18 flow diagram',
    },
    {
      id: 'BR-011',
      description: 'Missing doc request aborts the booking process. Booking is blocked (offline) until the DO is received. This is a hard stop, not a warning.',
      applies_to: ['booking', 'hbl'],
      source: 'March 18 flow diagram',
    },
    {
      id: 'BR-012',
      description: 'Booking confirmation is sent to the account email (LSP) or P4TC email only. No system email is sent to the driver — the booking party forwards the booking reference to the driver externally via their own rostering process.',
      applies_to: ['booking'],
      source: 'discussion between Roni and Matt on 2026-03-18',
    },
    {
      id: 'BR-013',
      description: 'P4TC can delegate shipments further to another P4TC by entering name + email. The new P4TC receives an email with shipment roster and secure link. Chain delegation is supported.',
      applies_to: ['p4tc', 'hbl'],
      source: 'March 18 flow diagram',
    },
    {
      id: 'BR-014',
      description: 'ACFS manages user lifecycle: create, update, remove LSP and ACFS internal users. Feature permissions can be configured per user.',
      applies_to: ['acfs', 'lsp'],
      source: 'March 18 flow diagram',
    },
    {
      id: 'BR-015',
      description: 'Booking modifications by external users: truck/driver can be changed at any time until shipment is collected (no cutoff restriction). Slot date/time and HBL changes (add/remove) allowed before change cutoff only. Cost-impacting changes after cutoff require ACFS admin intervention. ACFS admin can override all cutoffs.',
      applies_to: ['booking', 'lsp', 'p4tc', 'acfs'],
      source: 'discussion between Roni and Matt on 2026-03-18',
    },
    {
      id: 'BR-016',
      description: 'Driver records are scoped per LSP account. Drivers added by one LSP user are visible to all users within that same account, but NOT visible to other accounts. P4TC users do not have saved driver records.',
      applies_to: ['lsp', 'driver_record'],
      source: 'discussion between Roni and Matt on 2026-03-18',
    },
    {
      id: 'BR-017',
      description: 'Booking requires acceptance of two separate documents: (1) booking terms and conditions (legal), (2) driver site induction acknowledgement. If the selected driver already has site_induction = true, the induction acceptance is skipped.',
      applies_to: ['booking', 'driver_record'],
      source: 'discussion between Roni and Matt on 2026-03-18',
    },
    {
      id: 'BR-018',
      description: 'DO validation is HBL-centric, not booking-centric. It is a separate capability from pickup verification. Can be performed by an offshore team. Warehouse staff doing pickup verification may also validate DOs inline.',
      applies_to: ['hbl', 'acfs'],
      source: 'discussion between Roni and Matt on 2026-03-18',
    },
    {
      id: 'BR-019',
      description: 'Fee calculation: chargeable_weight (max of weight vs volume) per HBL × rate (single flat value). Sum individual HBL charges + minimum charge = total booking fee. Rate is a single configurable value for Phase 1 — may become per-slot or per-region in future.',
      applies_to: ['booking', 'hbl'],
      source: 'discussion between Roni and Matt on 2026-03-18',
    },
    {
      id: 'BR-020',
      description: 'Booking update notifications are sent to the booking party\'s account email when ACFS makes changes to a booking.',
      applies_to: ['booking', 'acfs'],
      source: 'discussion between Roni and Matt on 2026-03-18',
    },
    {
      id: 'BR-021',
      description: 'Each HBL requires either a DO upload or a free release flag — one or the other per shipment. Free release removes the DO requirement for that tier entirely. This is a per-HBL choice made during the booking readiness step.',
      applies_to: ['hbl', 'lsp', 'p4tc'],
      source: 'March 18 Miro board — "Either DO or Free release per shipment Free Release Flag"',
    },
    {
      id: 'BR-022',
      description: 'Booking cancellation: LSP can cancel their own bookings. ACFS can cancel any booking (requires cancellation reason). Cancellation notification sent to booking party. Refund processed outside the system. HBLs revert to previous status.',
      applies_to: ['booking', 'lsp', 'acfs'],
      source: 'March 18 Miro board — cancel booking flows',
    },
    {
      id: 'BR-023',
      description: 'P4TC (one-off booking party) cannot self-service modify bookings. Must contact ACFS for any changes.',
      applies_to: ['booking', 'p4tc'],
      source: 'March 18 Miro board — "CONTACT ACFS FOR ANY BOOKING MODIFICATIONS"',
    },
    {
      id: 'BR-024',
      description: 'User account removal is soft-delete (archive). Access is disabled and email notifications are disabled. User data is retained.',
      applies_to: ['acfs', 'lsp'],
      source: 'March 18 Miro board — "ARCHIVE USER ON REMOVAL"',
    },
    {
      id: 'BR-025',
      description: 'Welcome email signin link expires in 72 hours. User must click and set password (LSP) or complete SSO login (ACFS) within this window.',
      applies_to: ['acfs', 'lsp'],
      source: 'March 18 Miro board — "LINK EXPIRY 72 HOURS"',
    },
    {
      id: 'BR-026',
      description: 'Slots with active bookings cannot be removed. ACFS must cancel or reschedule bookings before removing a slot.',
      applies_to: ['slot', 'acfs'],
      source: 'March 18 Miro board — "ACTIVE BOOKINGS? YES → CANNOT REMOVE SLOT"',
    },
    {
      id: 'BR-027',
      description: 'Admin booking modifications (add/remove HBLs, change slot) are fee-free for Phase 1. When HBLs are added or removed, the fee total recalculates to reflect the new weight but no additional payment is collected. No truck capacity validation on HBL add — carrier\'s responsibility.',
      applies_to: ['booking', 'acfs'],
      source: 'discussion between Rahul and Roni on 2026-03-20',
    },
    {
      id: 'BR-028',
      description: 'Booking "collected" status is derived, not manually set. A booking becomes "collected" when all its HBLs reach the "collected" milestone. No manual status change needed.',
      applies_to: ['booking', 'hbl'],
      source: 'discussion between Rahul and Roni on 2026-03-20',
    },
    {
      id: 'BR-029',
      description: 'Audit trail: slim version on booking (booking created, payment confirmed). Full hop history lives on the HBL — shows all delegation chain hops, assignment changes, and status transitions per shipment.',
      applies_to: ['booking', 'hbl'],
      source: 'discussion between Rahul and Roni on 2026-03-20',
    },
    {
      id: 'BR-030',
      description: 'LSP "My Bookings" reuses the same booking list and detail view as the ACFS admin bookings interface. LSP can edit truck/driver at any time and slot/HBL before change cutoff (per BR-015). Same component as ACFS admin, different permissions.',
      applies_to: ['booking', 'lsp'],
      source: 'discussion between Rahul and Roni on 2026-03-20',
    },
    {
      id: 'BR-031',
      description: 'Multiple DOs per HBL — one DO per delegation tier (one-to-many relationship). Each DO is validated individually by ACFS. ACFS browses between DOs for a given HBL and marks each as validated or flagged.',
      applies_to: ['hbl', 'delivery_order', 'acfs'],
      source: 'discussion between Rahul and Roni on 2026-03-20',
    },
  ],
  constraints: [
    {
      id: 'C-001',
      constraint: 'Pickup slots have NO hard capacity limits. Density indicator only (low/moderate/high based on configurable threshold). Does NOT block booking. Per-site configuration. Nice-to-have for Phase 1.',
      type: 'capacity',
    },
    {
      id: 'C-002',
      constraint: 'Slots with existing bookings cannot be modified in Phase 1. Blackout dates enforced via holiday calendar overlay.',
      type: 'temporal',
    },
    {
      id: 'C-003',
      constraint: 'Refunds are completely outside the portal. Handled offline by ACFS. Portal is refund-agnostic.',
      type: 'pricing',
    },
    {
      id: 'C-004',
      constraint: 'Driver has no portal access. No system emails to driver. Booking party manages driver communication externally.',
      type: 'access',
    },
    {
      id: 'C-005',
      constraint: 'P4TC (one-off) has no persistent credentials. Services shipments via magic link + OTP only. No account history. No saved driver records.',
      type: 'access',
    },
    {
      id: 'C-006',
      constraint: 'Site management is DB-seeded for Phase 1 — no admin CRUD UI. Sites have name + branch code only.',
      type: 'admin',
    },
    {
      id: 'C-007',
      constraint: 'Desktop/laptop only. No tablet or mobile responsive design required. Portal is not meant for warehouse staff walking around — it is for counter/desk use.',
      type: 'platform',
    },
    {
      id: 'C-008',
      constraint: 'Email is the primary notification channel. In-app notifications are available for logged-in users (LSPs, ACFS) but are not a Phase 1 blocker. P4TC (no login) receives email only. DO flag-for-correction triggers email to booking party.',
      type: 'notification',
    },
  ],
  open_questions: [
    {
      id: 'OQ-034',
      question: 'What is the exact data source for HBL hierarchy relationships?',
      reason: 'Maximus has both lowest-level and master HBL references but NOT the parent-child relationship between them. AGS can provide the hierarchy. Matt and William are working on this — need confirmed approach before building the data integration.',
      status: 'open',
    },
  ],
}
