import { intentModel } from '../src/domain/intent-model/model'
import type { IntentModel, Entity, BusinessRule } from '../src/domain/intent-model/types'
import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const PORTAL_DIR = path.resolve(__dirname, '../../vbs-portal')
const CONTRACT_PATH = path.join(PORTAL_DIR, 'src/lib/intent-contract.ts')
const CHECKLIST_PATH = path.join(PORTAL_DIR, 'docs/intent-contract-rules-checklist.md')

// Preserve existing verified statuses
function loadExistingVerified(filePath: string): Map<string, boolean> {
  const map = new Map<string, boolean>()
  if (!fs.existsSync(filePath)) return map

  let content: string
  try {
    content = fs.readFileSync(filePath, 'utf-8')
  } catch {
    console.error(`Error reading existing contract file at ${filePath}. Aborting.`)
    process.exit(1)
  }

  // Extract only the contractRules section to avoid matching entity IDs
  const rulesSection = content.slice(content.indexOf('contractRules'))
  if (!rulesSection) return map

  // Parse verified values from contractRules entries
  const ruleRegex = /id:\s*["']([^"']+)["'][\s\S]*?verified:\s*(true|false)/g
  let match
  while ((match = ruleRegex.exec(rulesSection)) !== null) {
    map.set(match[1], match[2] === 'true')
  }

  // If file exists but no rules found, it may be corrupted — abort
  if (map.size === 0 && content.includes('contractRules')) {
    console.error('Existing contract file found but no rules could be parsed. Aborting to prevent data loss.')
    process.exit(1)
  }

  return map
}

function isIntegrationEntity(entity: Entity): boolean {
  return entity.id.startsWith('integration_')
}

function generateContract(model: IntentModel): string {
  const existingVerified = loadExistingVerified(CONTRACT_PATH)
  const domainEntities = model.entities.filter(e => !isIntegrationEntity(e))

  const entitiesStr = domainEntities.map(e => {
    const fields = e.key_fields.map(f => {
      const warn = f.warn ? `\n      warn: ${JSON.stringify(f.warn)},` : ''
      return `    {
      name: ${JSON.stringify(f.name)},
      type: ${JSON.stringify(f.type)},
      description: ${JSON.stringify(f.description)},${warn}
    }`
    }).join(',\n')

    const states = e.lifecycle.states.map(s => `'${s}'`).join(', ')

    const transitions = e.lifecycle.transitions.map(t => {
      const guard = t.guard ? `\n      guard: ${JSON.stringify(t.guard)},` : ''
      const warn = t.warn ? `\n      warn: ${JSON.stringify(t.warn)},` : ''
      return `    {
      from: ${JSON.stringify(t.from)},
      to: ${JSON.stringify(t.to)},
      trigger: ${JSON.stringify(t.trigger)},${guard}${warn}
    }`
    }).join(',\n')

    return `  {
    id: ${JSON.stringify(e.id)},
    name: ${JSON.stringify(e.name)},
    description: ${JSON.stringify(e.description)},
    fields: [
${fields}
    ],
    states: [${states}],
    transitions: [
${transitions}
    ],
  }`
  }).join(',\n')

  const rulesStr = model.business_rules.map(r => {
    const verified = existingVerified.get(r.id) ?? false
    const appliesTo = r.applies_to.map(a => `'${a}'`).join(', ')
    return `  {
    id: ${JSON.stringify(r.id)},
    description: ${JSON.stringify(r.description)},
    applies_to: [${appliesTo}],
    source: ${JSON.stringify(r.source)},
    verified: ${verified},
  }`
  }).join(',\n')

  return `// AUTO-GENERATED by vbs-intent/scripts/export-contract.ts
// Do not edit manually except for \`verified\` fields on rules.
// Re-run: cd ../vbs-intent && pnpm run export:contract

export type ContractMeta = {
  version: string
  project: string
  exportDate: string
  modelStatus: 'draft' | 'in_review' | 'approved'
}

export type ContractField = {
  name: string
  type: string
  description: string
  warn?: string
}

export type ContractTransition = {
  from: string
  to: string
  trigger: string
  guard?: string
  warn?: string
}

export type ContractEntity = {
  id: string
  name: string
  description: string
  fields: ContractField[]
  states: string[]
  transitions: ContractTransition[]
}

export type ContractRule = {
  id: string
  description: string
  applies_to: string[]
  source: string
  verified: boolean
}

export const contractMeta: ContractMeta = {
  version: ${JSON.stringify(model.meta.version)},
  project: ${JSON.stringify(model.meta.project)},
  exportDate: '${new Date().toISOString().split('T')[0]}',
  modelStatus: ${JSON.stringify(model.meta.status)},
}

export const contractEntities: ContractEntity[] = [
${entitiesStr}
]

export const contractRules: ContractRule[] = [
${rulesStr}
]
`
}

function generateChecklist(model: IntentModel): string {
  const lines = [
    '# Intent Model Business Rules Checklist',
    '',
    `Version: ${model.meta.version} | Generated: ${new Date().toISOString().split('T')[0]}`,
    '',
    '| Status | ID | Description | Applies To | Source |',
    '|---|---|---|---|---|',
  ]

  for (const rule of model.business_rules) {
    const appliesTo = rule.applies_to.join(', ')
    lines.push(`| [ ] | ${rule.id} | ${rule.description} | ${appliesTo} | ${rule.source} |`)
  }

  return lines.join('\n') + '\n'
}

// Main
const contract = generateContract(intentModel)
fs.writeFileSync(CONTRACT_PATH, contract, 'utf-8')
console.log(`Contract written to ${CONTRACT_PATH}`)

const checklist = generateChecklist(intentModel)
fs.writeFileSync(CHECKLIST_PATH, checklist, 'utf-8')
console.log(`Checklist written to ${CHECKLIST_PATH}`)
